import os
from pathlib import Path

from .templates.aerials.template import Template
from .base import write_file

import logging
log = logging.getLogger(__file__)


def create_coverages_dir(workspace_dir, aerials_dir):
    """
    add a softlink to the top level folder containing the .tiff files, 
    ala ln -s ~/aerials workspace/aerials/data
    """
    Path(workspace_dir).mkdir(exist_ok=True)
    aerials_link = os.path.join(workspace_dir, "data")
    Path(aerials_link).unlink(missing_ok=True)
    Path(aerials_link).symlink_to(Path(aerials_dir))


def create_workspace(data, workspaces_dir):
    from .templates.base_template import BaseTemplate

    # step 1: make the necessary workspace dirs, ala workspace/aerials
    aerials_workspace = os.path.join(workspaces_dir, data.get('workspace'))
    Path(aerials_workspace).mkdir(exist_ok=True)

    # step 2: make the workspace.xml file
    content = BaseTemplate.workspace(data)
    write_file(aerials_workspace, "workspace.xml", content)

    # step 3: make the workspace.xml file
    content = BaseTemplate.namespace(data)
    write_file(aerials_workspace, "namespace.xml", content)

    return aerials_workspace


def make_store(data, workspace_path, file_name="coveragestore.xml"):
    # step 1: make datasource folder
    dir_path = os.path.join(workspace_path, data.get('layer_id'))
    Path(dir_path).mkdir(exist_ok=True)

    # step 3: make the store config for the source
    content = Template.coverage_store(data)
    write_file(dir_path, file_name, content)

    # step 4: return the directory path to then write layers to this workspace
    return dir_path


def make_layer(data, layer_dir):
    """
    make 2nd layer folder, and populate it with coverage.xml and layer.xml files
    structure: 
      - aerial <dir>
      - aerial/coveragestore.xml
      - aerial/20ft/coverage.xml  : generated by ImageMosaic (has projection, etc...)
      - aerial/20ft/layer.xml     : typical GS layer.xml config
    """
    # step 1: make the layer dir, ala workspaces/aerials/6in/6in/
    dir_path = os.path.join(layer_dir, data.get('layer_id'))
    Path(dir_path).mkdir(exist_ok=True)

    # step 2: write the two layer files, ala coverage.xml layer.xml
    content = Template.coverage(data)
    write_file(dir_path, "coverage.xml", content)

    this_layer_id = f"Layer-{data['workspace']}-{data['layer_id']}"
    this_style_id = f"Style-{data['layer_id']}"
    data['this_layer_id'] = this_layer_id
    data['this_style_id'] = this_style_id
    content = Template.layer(data)
    write_file(dir_path, "layer.xml", content)


def make_layergroup(data, workspace_dir):
    # step 1: make the layergroups dir, ala workspaces/aerials/layergroups
    dir_path = os.path.join(workspace_dir, "layergroups")
    Path(dir_path).mkdir(exist_ok=True)

    # step 2: create layer group for the entire coverage with different rez's
    content = Template.layer_group(data)
    write_file(dir_path, f"{data.get('workspace')}.xml", content)


def make_gwc_layer(data, data_dir):
    # step 1: make the gwc-layers dir
    dir_path = os.path.join(data_dir, "gwc-layers")
    Path(dir_path).mkdir(exist_ok=True)

    # step 2: create the gwc-layer for our coverage, ala workspaces/gwc-layers/aerials.xml
    content = Template.gwc_layer(data)
    write_file(dir_path, f"{data.get('workspace')}.xml", content)


def generate(args, resolutions=["20ft", "10ft", "04ft", "02ft", "01ft", "6in"]):
    """ 
    gen geoserver aerial layer
    layers:
     - individual layer groups based on each gtfs feed (eg., trimet, ctran, sam, rideconnection, etc...)
     - current schema rollup
    """
    data = {'workspace': args.workspace}

    # step 1: make sure there's a data_dir folder for the layer information
    workspaces_dir = os.path.join(args.data_dir, "workspaces")
    Path(args.data_dir).mkdir(exist_ok=True)
    Path(workspaces_dir).mkdir(exist_ok=True)

    # step 2: create workspace.xml, namespace.xml and link to .tiff files
    aerials_workspace = create_workspace(data, workspaces_dir)
    create_coverages_dir(aerials_workspace, args.aerials_dir)

    # step 3: make the layers for each resoution of .tiff files
    for rez in resolutions:
        data['layer_id'] = rez

        # step 3a: get meta data and name for this feed / workspace
        dir_path = make_store(data, aerials_workspace)

        # step 3b: make route layer
        l = make_layer(data, dir_path)

    data['resolutions'] = resolutions
    make_layergroup(data, aerials_workspace)
    make_gwc_layer(data, args.data_dir)


def generate_geoserver_aerial_config(data_dir="data_dir", tiff_dir="aerials"):
    """
    defacto main statment to generate the config for aerials in the geoserver data_dir
    """
    def_params = {}
    def_params['dir'] = data_dir
    def_params['workspace'] = tiff_dir

    from ott.utils.parse.cmdline import osm_cmdline
    parser = osm_cmdline.geoserver_parser(def_params, "poetry run generate-geoserver-aerial-config", False)
    parser.add_argument(
        '--aerials_dir',
        '-aerials',
        '-ad',
        required=False,
        default=os.path.join(Path.home(), tiff_dir),
        help="the directory where the geotiff aerials live"
    )
    args = parser.parse_args()

    #import pdb; pdb.set_trace()
    generate(args)

