import os
from pathlib import Path

from .templates.aerials.template import Template
from .base import get_data, make_layergroup, make_feature, make_style_id

import logging
log = logging.getLogger(__file__)


def make_workspace(data, workspace_path, file_name="coveragestore.xml"):
    # step 1: make datasource folder for each schema
    dir_path = os.path.join(workspace_path, data.get('layer_id'))
    Path(dir_path).mkdir(exist_ok=True)

    # step 2: make the store config for the source
    cs_path = os.path.join(dir_path, file_name)
    with open(cs_path, 'w+') as f:
        content = Template.coverage_store(data)
        f.write(content)

    # step 3: return the directory path to then write layers to this workspace
    return dir_path


def create_coverages_dir(data_dir, aerials_dir):
    """
    does 2 things:
      1. create the data_dir/coverages folder
      2. create a soft link in data_dir/coverages to the geotiff 'aerials_dir' 
         (e.g., ln -s ~/aerials data_dir/coverages/aerials)
    """
    coverage_dir = os.path.join(data_dir, "coverages")
    aerials_link = os.path.join(coverage_dir, os.path.basename(aerials_dir))
    Path(coverage_dir).mkdir(exist_ok=True)
    Path(aerials_link).unlink(missing_ok=True)
    Path(aerials_link).symlink_to(Path(aerials_dir))


def create_coverage_layer():
    """
    structure: 
      - aerial <dir>
      - aerial/coveragestore.xml
      - aerial/aerial/coverage.xml  : generated by ImageMosaic (has projection, etc...)
      - aerial/aerial/layer.xml     : typical GS layer.xml config
    """
    # mkdir 


def generate(args, resolutions=["20ft", "10ft", "04ft", "02ft", "01ft", "6in"]):
    """ 
    gen geoserver aerial layer
    layers:
     - individual layer groups based on each gtfs feed (eg., trimet, ctran, sam, rideconnection, etc...)
     - current schema rollup
    """
    layers = []  # layers will store the layers for the layergroups.xml config
    data = {'workspace': args.workspace, 'type_name': 'xxxx', 'style_id': 'yyyy'}
    workspace_path = os.path.join(args.data_dir, "workspaces", args.workspace)
    Path(workspace_path).mkdir(exist_ok=True)    

    for rez in resolutions:
        data['layer_id'] = rez

        # step 1: get meta data and name for this feed / workspace
        dir_path = make_workspace(data, workspace_path)

        # step 2: make route layer
        l = make_feature(dir_path, data)
        layers.append(l)

    make_layergroup(workspace_path, data, layers, type_name='raw')


def generate_geoserver_aerial_config(data_dir="data_dir", tiff_dir="aerials"):
    """
    defacto main statment to generate the config for aerials in the geoserver data_dir
    """
    def_params = {}
    def_params['dir'] = data_dir
    def_params['workspace'] = tiff_dir

    from ott.utils.parse.cmdline import osm_cmdline
    parser = osm_cmdline.geoserver_parser(def_params, "poetry run generate-geoserver-aerial-config", False)
    parser.add_argument(
        '--aerials_dir',
        '-aerials',
        '-ad',
        required=False,
        default=os.path.join(Path.home(), tiff_dir),
        help="the directory where the geotiff aerials live"
    )
    args = parser.parse_args()

    #import pdb; pdb.set_trace()
    create_coverages_dir(args.data_dir, args.aerials_dir)
    generate(args)

